pipeline {
  agent any

  environment {
    APP_DIR = "spring-boot-app"
    MANIFEST_FILE = "spring-boot-app-manifests/deployment.yml"
    DOCKER_IMAGE = "yugandhar99/java-devsecops-cicd:${BUILD_NUMBER}"
    SONAR_URL = "http://sonar-server:9000"
    GIT_USER_NAME = "yugandhar99"
    GIT_REPO_NAME = "jenkins-java-devsecops-cicd"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build and Test') {
      steps {
        sh 'cd ${APP_DIR} && mvn clean package'
      }
    }

    stage('Static Code Analysis') {
      steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
          sh 'cd ${APP_DIR} && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
        }
      }
    }

    stage('Build and Push Docker Image') {
      steps {
        script {
          sh 'docker build -t ${DOCKER_IMAGE} ${APP_DIR}'
          def dockerImage = docker.image("${DOCKER_IMAGE}")
          docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
            dockerImage.push()
          }
        }
      }
    }

    stage('Trivy Image Scan') {
      steps {
        sh 'trivy image --exit-code 1 --severity HIGH,CRITICAL ${DOCKER_IMAGE}'
      }
    }

    stage('Update Kubernetes Manifest') {
      steps {
        withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
          sh '''
            git config user.email "yugandharethamukkala1999@gmail.com"
            git config user.name "Yugandhar Ethamukkala"
            sed -i "s|image: .*|image: ${DOCKER_IMAGE}|g" ${MANIFEST_FILE}
            git add ${MANIFEST_FILE}
            git commit -m "Update deployment image to build ${BUILD_NUMBER}" || echo "No manifest changes to commit"
            git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
          '''
        }
      }
    }
  }
}
